"""Import external gene data."""

import csv
import sys
from django.core.management.base import BaseCommand
from ...models import Gene

error_need_file = ("Please provide path to external gene data file as " +
                   "an argument.\nThis file should be generated by " +
                   "external_data/parse_external_data.py")

def add_external_gene_data(gene_data_filepath):
    """Adds external gene-related data to database."""
    try:
        gene_data_file = open(gene_data_filepath)
        gene_data = csv.reader(gene_data_file)
        gene_data.next()
        for row in gene_data:
            gene, unused = Gene.objects.get_or_create(hgnc_symbol=row[0],
                                                      hgnc_id=row[1],
                                                      hgnc_name=row[2],
                                                      ucsc_knowngene=row[3],
                                                      ncbi_gene_id=row[4])
            if row[5]:
                gene.mim_id = row[5]
            if row[6] and row[6] == 'Y':
                gene.clinical_testing = True
            if row[7] and row[7] == 'Y':
                gene.acmg_recommended = True
            gene.save()
    except IOError:
        print error_need_file


class Command(BaseCommand):
    help = 'Adds external gene-related data to database'

    def handle(self, *args, **options):
        try:
            add_external_gene_data(args[0])
        except IndexError:
            print error_need_file
